<a href="https://colab.research.google.com/github/piyushk4732/cognitive_computing/blob/main/Assignment6_NumPy_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Q1. Sensor readings

In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = temperature + 2
print("Corrected temperatures:", corrected_temperature)

fahrenheit = (9 / 5) * corrected_temperature + 32
print("Temperatures in Fahrenheit:", fahrenheit)

above_32 = corrected_temperature[corrected_temperature > 32]
print("Readings greater than 32°C:", above_32)

count = np.sum(corrected_temperature > 32)
print("Number of readings above 32°C:", count)

print("Vectorization applies the operation to the complete array at once, so there is no need to process each value separately with a loop. Boolean indexing also selects only the values that satisfy a condition, making the operation shorter and more efficient.")

Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperatures in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings above 32°C: 5
Vectorization applies the operation to the complete array at once, so there is no need to process each value separately with a loop. Boolean indexing also selects only the values that satisfy a condition, making the operation shorter and more efficient.


## Q2. Daily steps

In [2]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Total steps:", np.sum(steps))
print("Mean steps:", np.mean(steps))
print("Maximum steps:", np.max(steps))
print("Minimum steps:", np.min(steps))

print("Total steps for each day:", np.sum(steps, axis=0))
print("Total steps for each user:", np.sum(steps, axis=1))

max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum steps:", max_position)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum steps: (np.int64(3), np.int64(2))


## Q3. Array slicing, copying, reshaping and flattening

In [3]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:5]
subset[0] = 999

print("Original after modifying subset:", original)
print("Subset:", subset)

copied_array = original[1:5].copy()
copied_array[0] = 500

print("Original after modifying copied array:", original)
print("Copied array:", copied_array)

matrix = np.arange(1, 13).reshape(3, 4)
print("3 x 4 matrix:")
print(matrix)

print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1-2 and columns 2-3:")
print(matrix[0:2, 1:3])

flattened = matrix.flatten()
raveled = matrix.ravel()

print("Using flatten():", flattened)
print("Using ravel():", raveled)

raveled[0] = 100
print("Matrix after modifying ravel():")
print(matrix)
print("Raveled array:", raveled)

flattened[1] = 200
print("Matrix after modifying flatten():")
print(matrix)
print("Flattened array:", flattened)

print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original after modifying subset: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original after modifying copied array: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]
3 x 4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[2 3]
 [6 7]]
Using flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Using ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matrix after modifying ravel():
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Raveled array: [100   2   3   4   5   6   7   8   9  10  11  12]
Matrix after modifying flatten():
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flattened array: [  1 200   3   4   5   6   7   8   9  10  11  12]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


## Q4. Cognitive-assistive system

In [4]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

XT = X.T
print("X transpose:")
print(XT)

print("X.T @ X:")
print(XT @ X)

inverse = np.linalg.inv(XT @ X)
print("Inverse of X.T @ X:")
print(inverse)

beta = inverse @ XT @ y
print("OLS coefficients:", beta)

print("The three coefficients represent the effect of sleep hours, activity level, and stress level on the predicted assistance score when using the given linear model.")

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta

print("Predicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2
X transpose:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
OLS coefficients: [-0.15921454  0.14083853 10.06302242]
The three coefficients represent the effect of sleep hours, activity level, and stress level on the predicted assistance score when using the given linear model.
Predicted assistance score: 75.27862544779117
